name: isolated_http_client
description: http clint with requests cancelation and isolate decoding in separated isolate
version: 1.2.8
homepage: https://github.com/Renesanse/isolated_http_client

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  http: ^0.12.2
  meta: ^1.2.4
  worker_manager: ^3.2.8

dev_dependencies:
  lint: ^1.3.0
  test: ^1.14.4
