name: isolated_http_client
description: http clint with requests cancelation and isolate decoding in separated isolate
version: 1.4.0
homepage: https://github.com/Renesanse/isolated_http_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.2
  meta: ^1.3.0
  worker_manager: ^4.0.2
